name: Weather App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Python for backend
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install backend dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # Step 4: Run backend tests (if any)
      - name: Run tests
        working-directory: backend
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
        run: |
          if [ -d "tests" ]; then
            pytest tests
          else
            echo "No tests found, skipping..."
          fi

      # Step 5: Build Docker images
      - name: Build backend Docker image
        run: docker build -t weather-app-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t weather-app-frontend ./frontend

